### ISSUE TITLE
Bug: http://garnet.wdidc.org/events/1 should be 404, not 500

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/garnet#226]
Something has changed error handling.  If an item doesn't exist in the database, rails returns a 404 by default.  Is there a reason to change this?

- http://stackoverflow.com/questions/2385799/how-to-redirect-to-a-404-in-rails
- http://guides.rubyonrails.org/action_controller_overview.html#the-default-500-and-404-templates

**Comment by RobertAKARobin** [comment]
This, maybe? https://github.com/ga-dc/garnet/commit/d8ca0c8804ac633442c0cb5701235483318eb942

**Comment by adambray** [comment]
This is due to the `global_rescuer` code in `application_controller.rb`. Right now, we're swallowing all exceptions, and trying to redirect back. In this case, redirecting back fails, so it tries to redirect to the `error_path` which doesn't exist. A quick fix would be redirect to `root_url` instead, but honestly, I'd vote that we just remove the global rescuer code. It doesn't add much except allow us to display flash messages to the user, and as Matt has pointed out, it breaks web semantics (404, 500s errors, etc).
