### ISSUE TITLE
feature request: attendance filter user by classroom

### ISSUE THREAD

**Issue by jshawl** [ga-dc/garnet#278]

**Comment by RobertAKARobin** [comment]
We can already do this! We just need to create a group for each classroom and add the members to it.

**Comment by adambray** [comment]
Hmmm, I'm not sure creating groups for classrooms makes the most sense. Few potential issues:

* from a UX perspective, it's a bit tricky, since you have to go to different groups to do different tasks (take attendance / assignments / observations). This is already a problem, and I think encouraging us to do it this way only exacerbates the issue.
* students change memberships in classrooms, which means marking active / inactive in the classrooms groups. This is not only a UX issue, but I worry about data integrity, and it feels like not the intended use case.

Some other ways we could do it:

* add a `classroom` property on membership, and allow sorting and filtering on that
* one level higher in the abstraction tree: allow admins of a group to create and set custom attributes on a group, tied to each students membership (e.g. an admin could create a custom field for `squad`, or `favorite color` etc.

Really want to have a debate / brainstorming / discussion, but I'm feeling like there's a huge conceptual debt cost to our current "everything's a group in a tree" architecture.

**Comment by jshawl** [comment]
fixed w/ tags - https://github.com/ga-dc/garnet/pull/315
